Add double-quote filepath(css,to,base)
iwataka/minidown.vim pull request #2
Opened 2018-02-25 02:55 UTC by tsuyoshicho

#1 
Fixしてみました。Windowsでしか確認できなかったので、問題あるようでしたら却下してください。

2018-02-25 03:03 UTC, tsuyoshicho commented
ログがアレなのはrebase -iになれてないためです。スルーしてください...(取り込み時にログのcleanupする必要がありますね...)

2018-02-26 16:52 UTC, iwataka commented on autoload/minidown.vim
> +  let fname = '"'.fnamemodify(expand('%'), ':p').'"'
fname変数にダブルクオートが含まれるのは自分としては違和感があるので、26行目にダブルクオートを追加してもらった方が良いと思います。

2018-02-26 16:57 UTC, iwataka requested changes
6行目にもダブルクオートがなければ、空白を含むファイル名に対してブラウザが開かないはずなので、そこにまだ修正が必要だと思います。
あと他のところにも少々コメントさせていただきました。

修正していただければマージさせていただきますし、反応なければ自分の方で修正コミットを出します。

2018-02-27 13:58 UTC, tsuyoshicho commented
6行目自体は了解です(でもその対応なしで動作自体はOKでした、なんでだろ?)、どちらかというとおまかせしたほうがよさそうなので、その方向でおねがいします。

2018-02-27 16:37 UTC, iwataka commented
65a364fd09f5adf0eae4b6e5fac7f2ca06f12bd9
474bc08a06d1ebd905300bb825baaff350cc1ee1
修正しました。報告ありがとうございました。

2018-02-27 16:37 UTC, closed without merging